### ISSUE TITLE
[JACKGPT] Complete and consolidate the guidelines (PDF) with the text provided by Candice TRAN DAI (Group Security Office) ?

### ISSUE THREAD

**Issue by white-gorilla** [ELS-RD/chatbot-ui#9]

**Comment by ManuMateo** [comment]
The text sent from Candice on the 22/5 is already at the Guidelines PDF.

The only part is not included is the one that refers to ChatGPT, do we have to include it also? 

_Fonctionnement de ChatGPT :
Historique des conversations :
En cas de désactivation de l’historique, les nouvelles conversations seront supprimées dans les 30 jours et ne seront pas utilisées pour l’entraînement des modèles. Toutefois, les conversations existantes seront toujours sauvegardées et pourront être utilisées pour l’entraînement des modèles si l’utilisateur ne choisit pas de les exclure. Si l’historique est désactivé, les conversations ne peuvent être récupérées une fois qu’elles sont fermées.
Note sur la cybercriminalité liée à ChatGPT :
Cette note concerne spécifiquement l’usage personnel de ChatGPT via un compte personnel et via le Web public (c’est-à-dire en dehors du cadre de JackGPT)
L'utilisation de fausses applications ChatGPT pour notamment voler des informations d'identification personnelles est une tactique récente et connue, utilisée par les cybercriminels. 
Il existe actuellement une prolifération de fausses applications ChatGPT (« extension Google Chrome », « ChatGPT pour Windows »…) ainsi que des sites Web et des pages Web frauduleuses (fausses URL comme « chat-gpt-pc[.]online »). Il est important de noter qu'il n'y a à ce jour aucune application mobile ChatGPT officielle, ni de ChatGPT disponible en téléchargement.
ChatGPT est uniquement disponible sur la page Web officielle d'OpenAI : https://openai.com/blog/chatgpt_

![image](https://github.com/ELS-RD/chatbot-ui/assets/110182875/ed0bcbfe-f96f-42d0-82a0-5f012395463a)

**Comment by white-gorilla** [comment]
For me, "Fonctionnement de ChatGPT :" should not be included, as it relates to ChatGPT's conversation history, which we don't have in JackGPT.

I have no opinion on "Note sur la cybercriminalité liée à ChatGPT". It is not directly related to JackGPT, but can be considered as general information for those who might be tempted to use ChatGPT.

**Comment by ManuMateo** [comment]
I'll include it, but I'll remove this part as there is an official ChatGPT app: _Il est important de noter qu'il n'y a à ce jour aucune application mobile ChatGPT officielle, ni de ChatGPT disponible en téléchargement._

**Comment by white-gorilla** [comment]
You're right. Thanks Manu.

**Comment by ManuMateo** [comment]
Updated ¡¡¡ @white-gorilla can you check it?

A new section in the document has been added (chapter 1.4)



![Image](https://github.com/ELS-RD/chatbot-ui/assets/110182875/addc4114-a632-4a74-a891-5b9ebb6866b6)

**Comment by white-gorilla** [comment]
Nice. Thanks @ManuMateo. Approved.
